
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= Rails.application.credentials.database[:username] %>
  password: <%= Rails.application.credentials.database[:password] %>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: firepizza_development

test:
  <<: *default
  database: firepizza_test

production:
  <<: *default
  database: <%= Rails.application.credentials.production[:database] %>
  username: <%= Rails.application.credentials.production[:username] %>
  password: <%= Rails.application.credentials.production[:password] %>
